FROM tboquet/scikenacuthe7hc5

MAINTAINER Thomas Boquet <thomas.boquet@hec.ca>

RUN pip install dill

RUN pip install --upgrade git+git://github.com/tboquet/python-alp.git

CMD ["ipython", "notebook"]
